export { default as Loader } from './Loader'
export { default as Welcome } from './Welcome'
export { default as Footer } from './Footer'
export { default as Services } from './Services'
export { default as Spinner } from './Spinner'
export {default as Transactions} from './Transactions'
